/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsJobOpportunitiesRouteImport } from './routes/publications.job-opportunities'
import { Route as PublicationsAnnualReportsRouteImport } from './routes/publications.annual-reports'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as PublicationsJobOpportunitiesSlugRouteImport } from './routes/publications.job-opportunities.$slug'

const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsJobOpportunitiesRoute =
  PublicationsJobOpportunitiesRouteImport.update({
    id: '/job-opportunities',
    path: '/job-opportunities',
    getParentRoute: () => PublicationsRoute,
  } as any)
const PublicationsAnnualReportsRoute =
  PublicationsAnnualReportsRouteImport.update({
    id: '/annual-reports',
    path: '/annual-reports',
    getParentRoute: () => PublicationsRoute,
  } as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsJobOpportunitiesSlugRoute =
  PublicationsJobOpportunitiesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicationsJobOpportunitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/annual-reports': typeof PublicationsAnnualReportsRoute
  '/publications/job-opportunities': typeof PublicationsJobOpportunitiesRouteWithChildren
  '/publications/job-opportunities/$slug': typeof PublicationsJobOpportunitiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/annual-reports': typeof PublicationsAnnualReportsRoute
  '/publications/job-opportunities': typeof PublicationsJobOpportunitiesRouteWithChildren
  '/publications/job-opportunities/$slug': typeof PublicationsJobOpportunitiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/annual-reports': typeof PublicationsAnnualReportsRoute
  '/publications/job-opportunities': typeof PublicationsJobOpportunitiesRouteWithChildren
  '/publications/job-opportunities/$slug': typeof PublicationsJobOpportunitiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/publications'
    | '/programs/$slug'
    | '/publications/annual-reports'
    | '/publications/job-opportunities'
    | '/publications/job-opportunities/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publications'
    | '/programs/$slug'
    | '/publications/annual-reports'
    | '/publications/job-opportunities'
    | '/publications/job-opportunities/$slug'
  id:
    | '__root__'
    | '/'
    | '/publications'
    | '/programs/$slug'
    | '/publications/annual-reports'
    | '/publications/job-opportunities'
    | '/publications/job-opportunities/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicationsRoute: typeof PublicationsRouteWithChildren
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/job-opportunities': {
      id: '/publications/job-opportunities'
      path: '/job-opportunities'
      fullPath: '/publications/job-opportunities'
      preLoaderRoute: typeof PublicationsJobOpportunitiesRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/annual-reports': {
      id: '/publications/annual-reports'
      path: '/annual-reports'
      fullPath: '/publications/annual-reports'
      preLoaderRoute: typeof PublicationsAnnualReportsRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/job-opportunities/$slug': {
      id: '/publications/job-opportunities/$slug'
      path: '/$slug'
      fullPath: '/publications/job-opportunities/$slug'
      preLoaderRoute: typeof PublicationsJobOpportunitiesSlugRouteImport
      parentRoute: typeof PublicationsJobOpportunitiesRoute
    }
  }
}

interface PublicationsJobOpportunitiesRouteChildren {
  PublicationsJobOpportunitiesSlugRoute: typeof PublicationsJobOpportunitiesSlugRoute
}

const PublicationsJobOpportunitiesRouteChildren: PublicationsJobOpportunitiesRouteChildren =
  {
    PublicationsJobOpportunitiesSlugRoute:
      PublicationsJobOpportunitiesSlugRoute,
  }

const PublicationsJobOpportunitiesRouteWithChildren =
  PublicationsJobOpportunitiesRoute._addFileChildren(
    PublicationsJobOpportunitiesRouteChildren,
  )

interface PublicationsRouteChildren {
  PublicationsAnnualReportsRoute: typeof PublicationsAnnualReportsRoute
  PublicationsJobOpportunitiesRoute: typeof PublicationsJobOpportunitiesRouteWithChildren
}

const PublicationsRouteChildren: PublicationsRouteChildren = {
  PublicationsAnnualReportsRoute: PublicationsAnnualReportsRoute,
  PublicationsJobOpportunitiesRoute:
    PublicationsJobOpportunitiesRouteWithChildren,
}

const PublicationsRouteWithChildren = PublicationsRoute._addFileChildren(
  PublicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicationsRoute: PublicationsRouteWithChildren,
  ProgramsSlugRoute: ProgramsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
